/* Custom Fields */
#define PIN_FLD_INFO_NAI3               PIN_MAKE_FLD(PIN_FLDT_SUBSTRUCT, 10012)
#define PIN_FLD_INPUT_TOKENS_NAI3       PIN_MAKE_FLD(PIN_FLDT_INT, 10013)
#define PIN_FLD_OUTPUT_TOKENS_NAI3      PIN_MAKE_FLD(PIN_FLDT_INT, 10014)
#define PIN_FLD_PROMPT_NAI3             PIN_MAKE_FLD(PIN_FLDT_STR, 10015)
#define PIN_FLD_MODELTYPE_NAI3          PIN_MAKE_FLD(PIN_FLDT_STR, 10009)
